FROM python:2.7
MAINTAINER thy55661@msn.com

COPY ./BerkeleyProject /BerkeleyProject

WORKDIR /BerkeleyProject

RUN pip install -r requirements.txt

CMD ["python" , "manage.py", "runserver", "0.0.0.0:8000"]